# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28071c28f4d97f2fd44f96992e983df9e67ba6f0e878a5046c8e272912e40ab7b7fa1a48f6492d58231b2638e5cb0224b0e91f948123e327cd2f0d45089b47a8

test:
  secret_key_base: f7dea601bc0a3ee42abf6c3efc5bf1235950bbe0931a57a934d3087d66e8d522ef338ad16840ddf2aa9b46efe5a01dcde168e79f852d3afb4460c74aacbd2b11

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
